---
title: "Guia 1"
author: "Grupo 3"
date: "9/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
source('./PerceptronSimple.R')
source('./PerceptronMulticapa.R')
source('./Particiones.R')
```


## Or
```{r}

library(readr)

OR_trn <- read_csv("../PUBLICO/Encuentro 1/Práctica/data/OR_trn.csv", col_names = FALSE)

pesos <- entrenarPerceptron(OR_trn, maxEpocas = 10, critFinalizacion = 0.8)
pesos
```

```{r}
graficarRectaSeparacion(pesos, OR_trn)
```


## Punto 2

```{r}

# Test de funciones que devuelven los dataset completos.
particion_test <- generarParticion(dataset = OR_trn, porcEntrenamiento = 0.7, semilla = 1, 
                                   clase = "X3")

n_particion_test <- generarNParticiones(dataset = OR_trn, nroParticiones = 4, porcEntrenamiento = 0.75, 
                                  semilla = 1, clase = "X3")

# Test de funciones que devuelven los ID
particion_test_ID <- generarParticionPorID(dataset = OR_trn, porcEntrenamiento = 0.7, semilla = 1, 
                                   clase = "X3")

n_particion_test_ID <- generarNParticionesPorID(dataset = OR_trn, nroParticiones = 5, 
                                                porcEntrenamiento = 0.8, semilla = 1, 
                                                clase = "X3")

```






## Punto 3



```{r}

XOR_trn <- read_csv("../PUBLICO/Encuentro 1/Práctica/data/XOR_trn.csv", col_names = FALSE)
concentlite <- read_csv("../PUBLICO/Encuentro 1/Práctica/data/concentlite.csv", col_names = FALSE)

resultado <- entrenarPerceptronM(concentlite, maxEpocas = 300, critFinalizacion = 0.8, nu=0.01,
                                 arquitectura = c(5,1))


ggplot(data=concentlite, aes(x=X1, y=X2,color=X3))+geom_point()

```

```{r}

plot(resultado$error)

resultado$tasa

```

